---
- name: Creating the Filebeat Installation Play
  hosts: webservers
  become: True
  tasks:

      - name: download metricbeat deb
        command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

      - name: install metricbeat
        command: dpkg -i metricbeat-7.6.1-amd64.deb

      - name: metricbeat.yml
        copy:
          src: /etc/ansible/files/metricbeat-config.yml
          dest: /etc/metricbeat/metricbeat.yml

      - name: enable system
        command: metricbeat modules enable docker

      - name: metricbeat setup
        command: metricbeat setup

      - name: Mectricbeat on Boot
        systemd:
          name: metricbeat
          enabled: yes

      - name: start metricbeat service
        command: service metricbeat start -e
